# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audax < Formula
  desc "TUI tools for AWS administration"
  homepage "https://audax.tools"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_darwin_amd64.tar.gz"
      sha256 "4b102effcf99726bd0ec718de4c8634bed8896931c415a102add5bb607709731"

      def install
        bin.install "dynamo-browse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_darwin_arm64.tar.gz"
      sha256 "101bd0c70fde60a02b9e5e0c8f6e95ddce11802128dd2739442536f52dad41c5"

      def install
        bin.install "dynamo-browse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_linux_amd64.tar.gz"
      sha256 "3eb68dda8fc0dcae13bed5ef0f0a6919c92ec9a06f26865f838491fec8b8ee09"

      def install
        bin.install "dynamo-browse"
      end
    end
  end
end
