# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audax < Formula
  desc "TUI tools for AWS administration"
  homepage "https://audax.tools"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_darwin_arm64.tar.gz"
      sha256 "1c983a46d9679566ec7b5f9553113115ffc4b998ebf712fbe82b7a617d4c3ab6"

      def install
        bin.install "dynamo-browse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_darwin_amd64.tar.gz"
      sha256 "560f5f6abd160658579c6c955705d10fc9dfab76e667d1ae96325dac18bd475b"

      def install
        bin.install "dynamo-browse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.1.0/audax_0.1.0_linux_amd64.tar.gz"
      sha256 "a407a12caf78582968f37cb0f4407ce294fa40f6091b672c81d69a65620937f1"

      def install
        bin.install "dynamo-browse"
      end
    end
  end
end
